__1.__ Установить, какие произведения матриц $AB$ и $BA$ определены, и найти размерности полученных матриц:

   а) $A$ — матрица $4\times 2$, $B$ — матрица $4\times 2$;
    
   б) $A$ — матрица $2\times 5$, $B$ — матрица $5\times 3$;
    
   в) $A$ — матрица $8\times 3$, $B$ — матрица $3\times 8$;
    
   г) $A$ — квадратная матрица $4\times 4$, $B$ — квадратная матрица $4\times 4$.

а) $A\cdot B^{T},  B\cdot A^{T} $ - матрица  $4\times 4$

$A^{T}\cdot B,  B^{T}\cdot A $ - матрица  $2\times 2$

б)
$A\cdot B  $ - матрица  $2\times 3$

$B^{T}\cdot A^{T} $ - матрица  $3\times 2$

в)
$A\cdot B  $ - матрица  $8\times 8$

$B\cdot A  $ - матрица  $3\times 3$

$B^{T}\cdot A^{T} $ - матрица  $8\times 8$

$A^{T}\cdot B^{T} $ - матрица  $3\times 3$

в)
$A\cdot B,  A^{T}\cdot B^{T},  A^{T}\cdot B,  A\cdot B^{T}  $ - матрица  $4\times 4$

$B\cdot A,  B^{T}\cdot A^{T},  B^{T}\cdot A,  B\cdot A^{T}  $ - матрица  $4\times 4$

__2.__ Найти сумму и произведение матриц $A=\begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix}$ и $B=\begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix}.$

$$A = \begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix} B=\begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix}.$$

$$\begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix} +
\begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix} = 
\begin{pmatrix}
1 + 4 & (-2)+ (-1)\\ 
3 + 0 & 0 + 5
\end{pmatrix} = 
\begin{pmatrix}
5 & -3\\ 
3 & 5
\end{pmatrix}.
$$


$$\begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix} \cdot
\begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix} = 
\begin{pmatrix}
1\cdot 4 + (-2)\cdot 0 & 1\cdot(-1) + (-2)\cdot 5\\ 
3\cdot 4 + 0\cdot 0 & 3\cdot(-1) + 0\cdot 5
\end{pmatrix} = 
\begin{pmatrix}
4 & -11\\ 
12 & -3
\end{pmatrix}.
$$

__3.__ Из закономерностей сложения и умножения матриц на число можно сделать вывод, что матрицы одного размера образуют линейное пространство. Вычислить линейную комбинацию $3A-2B+4C$ для матриц $A=\begin{pmatrix}
1 & 7\\ 
3 & -6
\end{pmatrix}$, $B=\begin{pmatrix}
0 & 5\\ 
2 & -1
\end{pmatrix}$, $C=\begin{pmatrix}
2 & -4\\ 
1 & 1
\end{pmatrix}.$

$3\begin{pmatrix}
1 & 7\\ 
3 & -6
\end{pmatrix}$ $-2\begin{pmatrix}
0 & 5\\ 
2 & -1
\end{pmatrix}$ $+ 4\begin{pmatrix}
2 & -4\\ 
1 & 1
\end{pmatrix} =  
\begin{pmatrix}
3\cdot 1 + (-2)\cdot 0 + 4\cdot2 & 3\cdot 7 + (-2)\cdot 5 + 4\cdot(-4) \\ 
3\cdot 3 + (-2)\cdot 2 + 4\cdot1 & 3\cdot (-6) + (-2)\cdot (-1) + 4\cdot(1)
\end{pmatrix}= 
\begin{pmatrix}
11 & -5\\ 
9 & -12
\end{pmatrix}.$

__4.__ Дана матрица $A=\begin{pmatrix}
4 & 1\\ 
5 & -2\\ 
2 & 3
\end{pmatrix}$.
Вычислить $AA^{T}$ и $A^{T}A$.

$A=\begin{pmatrix}
4 & 1\\ 
5 & -2\\ 
2 & 3
\end{pmatrix}
A^{T}=\begin{pmatrix}
4 & 5 & 2\\ 
1 & -2 & 3\\ 
\end{pmatrix}$

 $ AA^{T}=
\begin{pmatrix}
4\cdot 4 + 1\cdot 1 & 4\cdot 5 + 1\cdot (-2) & 4\cdot 2 + 1\cdot 3\\ 
5\cdot 4 + (-2)\cdot 1 & 5\cdot 5 + (-2)\cdot (-2) & 5\cdot 2 + (-2)\cdot 3\\
2\cdot 4 + 3\cdot 1 & 2\cdot 5 + 3\cdot (-2) & 2\cdot 2 + 3\cdot 3\\ 
\end{pmatrix} = 
\begin{pmatrix}
17 & 18 & 11\\ 
18 & 29 & 4\\
11 & 4 & 13\\
\end{pmatrix}$.

$
A^{T}=\begin{pmatrix}
4 & 5 & 2\\ 
1 & -2 & 3\\ 
\end{pmatrix}
A=\begin{pmatrix}
4 & 1\\ 
5 & -2\\ 
2 & 3
\end{pmatrix}
$

$ A^{T}A=
\begin{pmatrix}
4\cdot 4 + 5\cdot 5 + 2\cdot 2 & 4\cdot 1 + 5\cdot (-2) + 2\cdot 3\\ 
1\cdot 4 + (-2)\cdot 5 + 3\cdot 2 & 1\cdot 1  + (-2)\cdot (-2) + 3\cdot 3\\ 
\end{pmatrix} = 
\begin{pmatrix}
45 & 0 \\ 
0 & 14\\
\end{pmatrix}$.

__5*.__ Написать на Python функцию для перемножения двух произвольных матриц, не используя NumPy.

In [ ]:
def (A,B)
    

### Вторая часть

__1.__ Вычислить определитель:

   a)

$$\begin{vmatrix}
sinx & -cosx\\ 
cosx & sinx
\end{vmatrix};$$

   б)
    
$$\begin{vmatrix}
4 & 2 & 3\\ 
0 & 5 & 1\\ 
0 & 0 & 9
\end{vmatrix};$$
    
   в)

$$\begin{vmatrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{vmatrix}.$$

а) $2(sinx + cosx)$

In [3]:
#б) так как матрица треугольного вида то определитель равен произведению элементов главной диагонали 
4 * 5 * 9

180

In [8]:
a = np.array([[4, 2, 3], [0, 5, 1], [0, 0, 9]])
print(f'Матрица:\n{a}')
print(f'Определитель:\n{np.linalg.det(a):.0f}')

Матрица:
[[4 2 3]
 [0 5 1]
 [0 0 9]]
Определитель:
180


In [6]:
import numpy as np
import scipy.linalg

в)

в данной матрице наблюдается линейная зависимость, поэтому определитель равен 0

In [7]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(f'Матрица:\n{a}')
print(f'Определитель:\n{np.linalg.det(a):.0f}')

Матрица:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Определитель:
0


__2.__ Определитель матрицы $A$ равен $4$. Найти:

   а) $det(A^{2})$;
    
   б) $det(A^{T})$;
    
   в) $det(2A)$.

а) $4^{2} = 16 $

б) $4$

в) $4 * 8 = 32$

__3.__  Доказать, что матрица

$$\begin{pmatrix}
-2 & 7 & -3\\ 
4 & -14 & 6\\ 
-3 & 7 & 13
\end{pmatrix}$$
   
вырожденная.

две строки данной матрицы находятся в линейной зависимости, значит определитель будет равен нулю и следовательно матрица окажется вырожденной или сингулярной.

__4.__ Найти ранг матрицы:

   а) $\begin{pmatrix}
1 & 2 & 3\\ 
1 & 1 & 1\\ 
2 & 3 & 4
\end{pmatrix};$

   б) $\begin{pmatrix}
0 & 0 & 2 & 1\\ 
0 & 0 & 2 & 2\\ 
0 & 0 & 4 & 3\\ 
2 & 3 & 5 & 6
\end{pmatrix}.$

а) 3 строка является суммой первой и второй и поэтому отбрасываем её
$\begin{pmatrix}
1 & 2 & 3\\ 
1 & 1 & 1\\ 
\end{pmatrix};$
ранг матрицы равен 2

In [23]:
a = np.array([[1, 2, 3], [1, 1, 1], [2, 3, 4]])
print(f'Матрица:\n{a}')
print(f'Определитель:\n{np.linalg.det(a):.0f}')
np.linalg.matrix_rank(a)

Матрица:
[[1 2 3]
 [1 1 1]
 [2 3 4]]
Определитель:
0


2

б) 3 строка является суммой первой и второй и поэтому отбрасываем её $\begin{pmatrix}
0 & 0 & 2 & 1\\ 
0 & 0 & 2 & 2\\ 
2 & 3 & 5 & 6
\end{pmatrix}$ ;  ранг матрицы равен 3

In [25]:
a = np.array([[0, 0, 2, 1], [0, 0, 2, 2],[0, 0, 4, 3], [2, 3, 4, 5]])
print(f'Матрица:\n{a}')
print(f'Определитель:\n{np.linalg.det(a):.0f}')
np.linalg.matrix_rank(a)

Матрица:
[[0 0 2 1]
 [0 0 2 2]
 [0 0 4 3]
 [2 3 4 5]]
Определитель:
0


3