## Первая часть

__1.__ Решить систему уравнений методом Гаусса:

$$\begin{cases}
x_{1}+x_{2}-x_{3}-2x_{4}=0, \\
2x_{1}+x_{2}-x_{3}+x_{4}=-2, \\
x_{1}+x_{2}-3x_{3}+x_{4}=4.
\end{cases}$$

$\begin{pmatrix}
\left.\begin{matrix}
1 & 1 & -1 & -2 \\ 
2 & 1 & -1 & 1 \\ 
1 & 1 & -3 & 1
\end{matrix}\right|
\begin{matrix}
0\\ 
-2\\
4
\end{matrix}
\end{pmatrix}$

Вычтем из второй сторки первую умноженную на 2:

$\begin{pmatrix}
\left.\begin{matrix}
1 & 1 & -1 & -2 \\ 
0 & -1 & 1 & 5 \\ 
1 & 1 & -3 & 1
\end{matrix}\right|
\begin{matrix}
0\\ 
-2\\
4
\end{matrix}
\end{pmatrix}$

Вычтем из третей первую:

$\begin{pmatrix}
\left.\begin{matrix}
1 & 1 & -1 & -2 \\ 
0 & -1 & 1 & 5 \\ 
0 & 0 & -2 & 3
\end{matrix}\right|
\begin{matrix}
0\\ 
-2\\
4
\end{matrix}
\end{pmatrix}$

__2.__ Проверить на совместность и выяснить, сколько решений будет иметь система линейных уравнений:

   а) $\begin{cases}
3x_{1}-x_{2}+x_{3}=4, \\
2x_{1}-5x_{2}-3x_{3}=-17, \\
x_{1}+x_{2}-x_{3}=0;
\end{cases}$
    
   б) $\begin{cases}
2x_{1}-4x_{2}+6x_{3}=1, \\
x_{1}-2x_{2}+3x_{3}=-2, \\
3x_{1}-6x_{2}+9x_{3}=5;
\end{cases}$
    
   в) $\begin{cases}
x_{1}+2x_{2}+5x_{3}=4, \\
3x_{1}+x_{2}-8x_{3}=-2. 
\end{cases}$

а) Решение:

$\begin{pmatrix}
\left.\begin{matrix}
3 & -1 & 1  \\ 
2 & -5 & -3  \\ 
1 & 1 & -1 
\end{matrix}\right|
\begin{matrix}
4\\ 
-17\\
0
\end{matrix}
\end{pmatrix}$

In [2]:
import numpy as np

In [7]:
a = np.array([[3, -1, 1], [2, -5, -3], [1, 1, -1]])
print(f'Матрица:\n{a}')
print(f'Определитель:\n{np.linalg.det(a):.0f}')

Матрица:
[[ 3 -1  1]
 [ 2 -5 -3]
 [ 1  1 -1]]
Определитель:
32


а) ОТВЕТ: Число уравнений равно числу неизвестных и матрица коэффициентов невырождена т.к. определитеь не равен нулю и соответственно векторы столбцов коэффициентов линейно независимы, то такая система совместна, и ее решение единственно при любом векторе свободных членов.

б) Решение:

$\begin{pmatrix}
\left.\begin{matrix}
2 & -4 & 6  \\ 
1 & -2 & 3  \\ 
3 & -6 & 9 
\end{matrix}\right|
\begin{matrix}
1\\ 
-2\\
5
\end{matrix}
\end{pmatrix}$

In [8]:
a = np.array([[2, -4, 6], [1, -2, 3], [3, -6, 9]])
print(f'Матрица:\n{a}')
print(f'Определитель:\n{np.linalg.det(a):.0f}')

Матрица:
[[ 2 -4  6]
 [ 1 -2  3]
 [ 3 -6  9]]
Определитель:
0


ОТВЕТ: Число уравнений равно числу неизвестных и матрица коэффициентов вырождена т.к. определитеь равен нулю и соответственно векторы столбцов коэффициентов линейно зависимы, а так как вектор свободных членов не принадлежит этому подпространству то такая система несовместна и решений не имеет.

в) Решение:

$\begin{pmatrix}
\left.\begin{matrix}
1 & 2 & 5  \\ 
3 & 1 & -8   
 \end{matrix}\right|
\begin{matrix}
4\\ 
-2
\end{matrix}
\end{pmatrix}$

ОТВЕТ: Число уравнений меньше числа неизвестных, векторы столбцов коэффициентов линейно не зависимы, а так как вектор свободных членов не принадлежит этому подпространству то такая система несовместна и имеет бесконечное количество решений.

__3.__ Проверить на совместность и выяснить, сколько решений будет иметь система линейных уравнений, заданная расширенной матрицей

$$\tilde{A}=\begin{pmatrix}
\left.\begin{matrix}
1 & 3 & -2 & 4\\ 
0 & 5 & 0 & 1\\ 
0 & 0 & 3 & 0\\ 
0 & 0 & 0 & 2
\end{matrix}\right|
\begin{matrix}
3\\ 
2\\
4\\
1
\end{matrix}
\end{pmatrix}.$$

$rankA=rank \tilde A=4$, где $n=4$ — число неизвестных, то система определена, т. е. имеет единственное решение;

__4.__ Дана система линейных уравнений, заданная расширенной матрицей

$$\tilde{A}=\begin{pmatrix}
\left.\begin{matrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{matrix}\right|
\begin{matrix}
a\\ 
b\\
c
\end{matrix}
\end{pmatrix}.$$

Найти соотношение между параметрами $a$, $b$ и $c$, при которых система является несовместной.

Ответ: Вектор (a,b,c) соотношение между переменными не должно быть равным 3

## Вторая часть

__1.__ Решить систему уравнений методом Крамера:

   а) $\begin{cases}
x_{1}-2x_{2}=1 \\
3x_{1}-4x_{2}=7
\end{cases}$
    
   б) $\begin{cases}
2x_{1}-x_{2}+5x_{3}=10 \\
x_{1}+x_{2}-3x_{3}=-2 \\
2x_{1}+4x_{2}+x_{3}=1
\end{cases}$

а) Решение:

In [12]:
a = np.array([[1, -2], [3, -4]])
print(f'Матрица:\n{a}')
print(f'Определитель:\n{np.linalg.det(a):.0f}')

Матрица:
[[ 1 -2]
 [ 3 -4]]
Определитель:
2


Определитель не равен нулю значит система совместна.
Найдём определители

In [10]:
a = np.array([[1, -2], [7, -4]])
print(f'Матрица:\n{a}')
print(f'Определитель:\n{np.linalg.det(a):.0f}')

Матрица:
[[ 1 -2]
 [ 7 -4]]
Определитель:
10


In [14]:
a = np.array([[1, 1], [3,7]])
print(f'Матрица:\n{a}')
print(f'Определитель:\n{np.linalg.det(a):.0f}')

Матрица:
[[1 1]
 [3 7]]
Определитель:
4


$$x_{i}=\frac{detA_{i}}{detA}$$

In [16]:
10/2

5.0

In [17]:
4/2

2.0

### Ответ: $x_{1} = 5$, $x_{2} = 2$  

б) Решение:

In [19]:
a = np.array([[2, -1, 5], [1, 1, -3], [2, 4, 1]])
print(f'Матрица:\n{a}')
print(f'Определитель:\n{np.linalg.det(a):.0f}')

Матрица:
[[ 2 -1  5]
 [ 1  1 -3]
 [ 2  4  1]]
Определитель:
43


In [20]:
a = np.array([[10, -1, 5], [-2, 1, -3], [1, 4, 1]])
print(f'Матрица:\n{a}')
print(f'Определитель:\n{np.linalg.det(a):.0f}')

Матрица:
[[10 -1  5]
 [-2  1 -3]
 [ 1  4  1]]
Определитель:
86


In [21]:
a = np.array([[2, 10, 5], [1, -2, -3], [2, 1, 1]])
print(f'Матрица:\n{a}')
print(f'Определитель:\n{np.linalg.det(a):.0f}')

Матрица:
[[ 2 10  5]
 [ 1 -2 -3]
 [ 2  1  1]]
Определитель:
-43


In [22]:
a = np.array([[2, -1, 10], [1, 1, -2], [2, 4, 1]])
print(f'Матрица:\n{a}')
print(f'Определитель:\n{np.linalg.det(a):.0f}')

Матрица:
[[ 2 -1 10]
 [ 1  1 -2]
 [ 2  4  1]]
Определитель:
43


In [23]:
86/43, -43/43, 43/43

(2.0, -1.0, 1.0)

### Ответ: $x_{1} = 2$, $x_{2} = -1$ , $x_{3} = 1$ 

__3*.__ Решить систему линейных уравнений методом $LU$-разложения

$$\begin{cases}
2x_{1}+x_{2}+3x_{3}=1 \\
11x_{1}+7x_{2}+5x_{3}=-6 \\
9x_{1}+8x_{2}+4x_{3}=-5
\end{cases}$$

__4*.__ Решить систему линейных уравнений методом Холецкого

$$\begin{cases}
81x_{1}-45x_{2}+45x_{3}=531 \\
-45x_{1}+50x_{2}-15x_{3}=-460 \\
45x_{1}-15x_{2}+38x_{3}=193
\end{cases}$$

__5*.__ Написать на Python программу с реализацией одного из изученных алгоритмов решения СЛАУ.